# Generated by Django 5.2.11 on 2026-04-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_alter_cotizacionmotocicleta_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="motocicleta",
            name="caracteristicas",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="motocicleta",
            name="cilindraje",
            field=models.IntegerField(default=125),
        ),
        migrations.AddField(
            model_name="motocicleta",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="motocicletas/"),
        ),
        migrations.AddField(
            model_name="motocicleta",
            name="referencia",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="motocicleta",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("DEPORTIVA", "Deportiva"),
                    ("URBANA", "Urbana"),
                    ("TODOTERRENO", "Todoterreno"),
                    ("CUATRIMOTOS", "Cuatrimotos"),
                    ("AUTOMATICA", "Automáticas y Semiautomáticas"),
                ],
                default="URBANA",
                max_length=20,
            ),
        ),
    ]
