# Generated by Django 5.2.11 on 2026-04-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_motocicleta_caracteristicas_motocicleta_cilindraje_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motocicleta",
            name="cilindraje",
            field=models.IntegerField(),
        ),
    ]
