# Generated by Django 5.2.11 on 2026-04-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_alter_motocicleta_cilindraje"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="motocicleta",
            name="modelo",
        ),
        migrations.AlterField(
            model_name="motocicleta",
            name="marca",
            field=models.CharField(default="Yamaha", editable=False, max_length=80),
        ),
        migrations.AlterField(
            model_name="motocicleta",
            name="referencia",
            field=models.CharField(max_length=80),
        ),
    ]
