# Generated by Django 5.2.11 on 2026-04-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_remove_motocicleta_modelo_alter_motocicleta_marca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cotizacionmotocicleta",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="interesrepuesto",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="motocicleta",
            name="cilindraje",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="motocicleta",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="motocicleta",
            name="precio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="repuesto",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
