# Generated by Django 5.2.11 on 2026-04-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_hu10_cotizacion_motocicleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motocicleta',
            name='tipo',
            field=models.CharField(choices=[('DEPORTIVA', 'Deportiva'), ('URBANA', 'Urbana'), ('TODOTERRENO', 'Todoterreno'), ('CUATRIMOTOS', 'Cuatrimotos'), ('AUTOMATICA', 'Automaticas y Semiautomaticas')], default='URBANA', max_length=20),
        ),
    ]
