# Generated by Django 5.2.11 on 2026-03-15 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_alter_municipio_id_alter_sede_id_local"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cita",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[("LIBRE", "Libre"), ("ASIGNADA", "Asignada")], default="LIBRE", max_length=20
                    ),
                ),
                (
                    "tipo_servicio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANTENIMIENTO", "Mantenimiento General"),
                            ("REVISION", "Revisión General"),
                            ("ALISTAMIENTO", "Alistamiento"),
                            ("GARANTIA", "Revisión por Garantía"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("cliente_nombre", models.CharField(blank=True, default="", max_length=120)),
                ("cliente_documento", models.CharField(blank=True, default="", max_length=20)),
                ("cliente_telefono", models.CharField(blank=True, default="", max_length=20)),
                ("cliente_correo", models.EmailField(blank=True, default="", max_length=254)),
                ("placa_moto", models.CharField(blank=True, default="", max_length=10)),
                ("referencia_moto", models.CharField(blank=True, default="", max_length=60)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="citas", to="core.local"
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora_inicio"],
            },
        ),
    ]
