# Generated by Django 5.2.11 on 2026-03-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0002_cita_anio_moto_cita_tipo_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="correo_confirmacion_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cita",
            name="error_envio_confirmacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cita",
            name="fecha_envio_confirmacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
