# Generated by Django 5.2.11 on 2026-03-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_cita_correo_confirmacion_enviado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="correo_cancelacion_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="cita",
            name="error_envio_cancelacion",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="cita",
            name="fecha_envio_cancelacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[("LIBRE", "Libre"), ("ASIGNADA", "Asignada"), ("CANCELADA", "Cancelada")],
                default="LIBRE",
                max_length=20,
            ),
        ),
    ]
