# Generated by Django 5.2.11 on 2026-05-15 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_local_servicios"),
        ("scheduling", "0006_alter_cita_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitaCancelada",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cita_original_id", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "tipo_servicio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MANTENIMIENTO", "Mantenimiento General"),
                            ("REVISION", "Revisión General"),
                            ("ALISTAMIENTO", "Alistamiento"),
                            ("GARANTIA", "Revisión por Garantía"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        blank=True,
                        choices=[("CC", "Cédula de ciudadanía"), ("CE", "Cédula de extranjería"), ("PP", "Pasaporte")],
                        default="",
                        max_length=5,
                    ),
                ),
                ("cliente_nombre", models.CharField(blank=True, default="", max_length=120)),
                ("cliente_documento", models.CharField(blank=True, default="", max_length=20)),
                ("cliente_telefono", models.CharField(blank=True, default="", max_length=20)),
                ("cliente_correo", models.EmailField(blank=True, default="", max_length=254)),
                ("placa_moto", models.CharField(blank=True, default="", max_length=10)),
                ("referencia_moto", models.CharField(blank=True, default="", max_length=60)),
                ("anio_moto", models.PositiveIntegerField(blank=True, null=True)),
                ("fecha_cancelacion", models.DateTimeField(auto_now_add=True)),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="citas_canceladas", to="core.local"
                    ),
                ),
            ],
            options={
                "ordering": ["fecha", "hora_inicio", "fecha_cancelacion"],
            },
        ),
    ]
