# Generated by Django 5.2.11 on 2026-03-15 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_municipio_id_alter_sede_id_local"),
        ("users", "0002_alter_user_options_remove_user_role_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="local",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="administradores",
                to="core.local",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
