# Generated by Django 5.2.11 on 2026-03-15 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipio",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="sede",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=120)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=20)),
                ("correo_admin", models.EmailField(max_length=254)),
                ("descripcion", models.TextField(blank=True, default="")),
                ("hora_apertura", models.TimeField()),
                ("hora_cierre", models.TimeField()),
                ("num_mecanicos", models.PositiveIntegerField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "sede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="locales", to="core.sede"
                    ),
                ),
            ],
        ),
    ]
