# Generated by Django 5.2.11 on 2026-04-21 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diagnostics", "0004_alter_diagnostico_options_alter_diagnostico_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnostico",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="evidencia",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="radicado",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
